---
- name: Install some packages needed for the GitLab installation(RedHat)
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - curl
      - policycoreutils
      - openssh-server
      - openssh-clients
      - postfix

