---
- name: Check if kubelet.conf exists
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- name: Copy the join command to server location
  when: not kubelet_conf.stat.exists
  copy:
    src: /tmp/join-command
    dest: /tmp/join-command.sh
    mode: 0700

- name: Join the node to cluster
  when: not kubelet_conf.stat.exists
  command: sh /tmp/join-command.sh

- name: Remove join-command.sh
  file:
    path: /tmp/join-command.sh
    state: absent
