---
- hosts: k8s cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: k8s master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: k8s worker
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }